databases:
  - name: chess-db
    databaseName: modernchess
    user: chessuser
    plan: free

services:
  - type: web
    name: modern-chess
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn myproject.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: chess-db
          property: connectionString
      - key: WEB_CONCURRENCY
        value: 4
